apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: eversonsilva7/library:latest
        ports:
        - containerPort: 80
		env:
		- name: ASPNETCORE_URLS
		  value: http://*:80
